export type Product = {
  id: number;
  name: string;
  price: number;
  rating: number;
  image: string;
  category: string;
  description: string;
  courier: string[];
};

export const products: Product[] = [
  {
    id: 1,
    name: 'Premium Wireless Headphones',
    price: 4499000,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
    category: 'Electronics',
    description: 'High-quality wireless headphones with noise cancellation technology.',
    courier: ['JNE', 'SiCepat', 'GoSend'],
  },
  {
    id: 2,
    name: 'Classic Leather Watch',
    price: 2999000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
    category: 'Accessories',
    description: 'Elegant leather watch with premium craftsmanship.',
    courier: ['JNE', 'SiCepat'],
  },
  {
    id: 3,
    name: 'Modern Desk Lamp',
    price: 899000,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
    category: 'Home & Living',
    description: 'Contemporary desk lamp with adjustable brightness.',
    courier: ['JNE', 'GoSend'],
  },
  {
    id: 4,
    name: 'Casual Sneakers',
    price: 1299000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    category: 'Fashion',
    description: 'Comfortable casual sneakers for everyday wear.',
    courier: ['JNE', 'SiCepat', 'GoSend'],
  },
  // Additional products
  {
    id: 5,
    name: 'Smart Fitness Tracker',
    price: 1899000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6',
    category: 'Electronics',
    description: 'Advanced fitness tracker with heart rate monitoring.',
    courier: ['JNE', 'SiCepat'],
  },
  {
    id: 6,
    name: 'Leather Messenger Bag',
    price: 2499000,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62',
    category: 'Accessories',
    description: 'Stylish leather messenger bag for professionals.',
    courier: ['JNE', 'GoSend'],
  },
  {
    id: 7,
    name: 'Minimalist Wall Clock',
    price: 599000,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c',
    category: 'Home & Living',
    description: 'Modern wall clock with silent movement.',
    courier: ['JNE', 'SiCepat'],
  },
  {
    id: 8,
    name: 'Denim Jacket',
    price: 1799000,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9',
    category: 'Fashion',
    description: 'Classic denim jacket with modern fit.',
    courier: ['JNE', 'SiCepat', 'GoSend'],
  },
  {
    id: 9,
    name: 'Wireless Earbuds',
    price: 2299000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
    category: 'Electronics',
    description: 'True wireless earbuds with premium sound quality.',
    courier: ['JNE', 'GoSend'],
  },
  {
    id: 10,
    name: 'Sunglasses',
    price: 999000,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083',
    category: 'Accessories',
    description: 'Stylish sunglasses with UV protection.',
    courier: ['JNE', 'SiCepat'],
  },
  {
    id: 11,
    name: 'Table Lamp',
    price: 799000,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1543198126-c78d0d4d1e66',
    category: 'Home & Living',
    description: 'Modern table lamp with ambient lighting.',
    courier: ['JNE', 'SiCepat', 'GoSend'],
  },
  {
    id: 12,
    name: 'Running Shoes',
    price: 1599000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    category: 'Fashion',
    description: 'Professional running shoes with superior comfort.',
    courier: ['JNE', 'GoSend'],
  },
  {
    id: 13,
    name: 'Smart Watch',
    price: 3499000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
    category: 'Electronics',
    description: 'Advanced smartwatch with health monitoring features.',
    courier: ['JNE', 'SiCepat'],
  },
  {
    id: 14,
    name: 'Leather Wallet',
    price: 699000,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93',
    category: 'Accessories',
    description: 'Genuine leather wallet with RFID protection.',
    courier: ['JNE', 'SiCepat', 'GoSend'],
  },
  {
    id: 15,
    name: 'Throw Pillows',
    price: 399000,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6',
    category: 'Home & Living',
    description: 'Decorative throw pillows with premium fabric.',
    courier: ['JNE', 'GoSend'],
  },
  {
    id: 16,
    name: 'Winter Jacket',
    price: 2899000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3',
    category: 'Fashion',
    description: 'Warm winter jacket with water-resistant material.',
    courier: ['JNE', 'SiCepat'],
  },
];